project_id = "dyadacivhjauywiwqoxb"

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.confirm-manual-payment]
verify_jwt = false

[functions.send-email]
verify_jwt = false
